
name: Build Auto APKs

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@v1.0.0
